[theme]
base="light"
primaryColor="#004a55"
backgroundColor="#fafafa"
textColor="#222"
font="sans serif"

[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 1000